version: '3.1'

services:
  app:
    build: .
    command: npm run build
    environment:
      NODE_ENV: production
    ports:
      - '3333:3333'
    volumes:
      - .:/home/app/appDir
      - /home/app/appDir/node_modules
